/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdoc_java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(App.getConnection(), "app should be connected to db");
    }
}
